// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// AAOS Build targets pipeline.

def getAndroidVersion(revision) {
  if (revision =~ "android-14") {
    return "14"
  } else if (revision =~ "android-15") {
    return "15"
  } else if (revision =~ "android-16") {
    return "16"
  } else {
    currentBuild.result = 'FAILURE'
    error "Failed to determine Android version from revision: ${revision}"
  }
}

pipeline {

  // Parameters defined in groovy/job.groovy

  agent none

  environment {
    GERRIT_API_URL="https://${env.HORIZON_DOMAIN}/gerrit"
    POD_TEMPLATE = "${USE_LOCAL_AOSP_MIRROR == "true" ? kubernetesPodTemplateWithMirror : kubernetesPodTemplateWithoutMirror}"

    def androidVersion="${ANDROID_VERSION != "default" ? ANDROID_VERSION : getAndroidVersion(AAOS_REVISION)}"
    def rpi="${AAOS_LUNCH_TARGET =~ "rpi" ? "-rpi" : ""}"
    SDK_ANDROID_VERSION="${androidVersion}"
    STORAGE_CLASS_SUFFIX="android-${androidVersion}"+"${rpi}"
    STORAGE_SIZE="${STORAGE_CLASS_SUFFIX =~ "rpi" ? "500Gi" : "1000Gi"}"

    // Define Pod Template in environment so we can override storageClassName.

    // Pod template WITHOUT AOSP Mirror volume mounted
    def kubernetesPodTemplateWithoutMirror = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          aaos_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: android
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-aaos-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            appArmorProfile:
              type: Unconfined
          command:
          - sleep
          args:
          - 5h
          resources:
            limits:
              cpu: 16000m
              memory: 64Gi
            requests:
              cpu: 16000m
              memory: 64Gi
          volumeMounts:
            - mountPath: /aaos-cache
              name: aaos-cache
        volumes:
          - name: aaos-cache
            ephemeral:
              volumeClaimTemplate:
                spec:
                  storageClassName: ${JENKINS_AAOS_BUILD_CACHE_STORAGE_PREFIX}-${STORAGE_CLASS_SUFFIX}
                  resources:
                    requests:
                      storage: ${STORAGE_SIZE}
                  accessModes:
                    - ReadWriteOnce
        nodeSelector:
          workloadLabel: android
    """.stripIndent()

    // Pod template with AOSP Mirror volume mounted as read-only
    def kubernetesPodTemplateWithMirror = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          aaos_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: android
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-aaos-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            appArmorProfile:
              type: Unconfined
          command:
          - sleep
          args:
          - 5h
          resources:
            limits:
              cpu: 16000m
              memory: 64Gi
            requests:
              cpu: 16000m
              memory: 64Gi
          volumeMounts:
            - mountPath: /aaos-cache
              name: aaos-cache
            - mountPath: ${AOSP_MIRROR_PRESET_FILESTORE_PVC_MOUNT_PATH_IN_CONTAINER}
              readOnly: true
              name: ${AOSP_MIRROR_PRESET_FILESTORE_PVC_NAME}
        volumes:
          - name: aaos-cache
            ephemeral:
              volumeClaimTemplate:
                spec:
                  storageClassName: ${JENKINS_AAOS_BUILD_CACHE_STORAGE_PREFIX}-${STORAGE_CLASS_SUFFIX}
                  resources:
                    requests:
                      storage: ${STORAGE_SIZE}
                  accessModes:
                    - ReadWriteOnce
          - name: ${AOSP_MIRROR_PRESET_FILESTORE_PVC_NAME}
            persistentVolumeClaim:
              claimName: ${AOSP_MIRROR_PRESET_FILESTORE_PVC_NAME}
        nodeSelector:
          workloadLabel: android
    """.stripIndent()
  }

  stages {
    stage ('Start VM Instance') {
      agent { kubernetes { yaml "${POD_TEMPLATE}" } }
      stages {
        stage ('Clean') {
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { env.AAOS_CLEAN != 'NO_CLEAN' }
            }
          }
          steps {
            script {
              currentBuild.description = "${env.AAOS_LUNCH_TARGET}" + "<br/>" + "${env.AAOS_REVISION}" + "<br/>" + "$BUILD_USER"
            }
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_CLEAN="${AAOS_CLEAN}" \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_environment.sh
                '''
              }
            }
          }
        }

        stage ('Initialise') {
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            script {
              currentBuild.description = "${env.AAOS_LUNCH_TARGET}" + "<br/>" + "${env.AAOS_REVISION}" + "<br/>" + "$BUILD_USER"
            }
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                withCredentials([usernamePassword(credentialsId: env.GERRIT_CREDENTIALS_ID, passwordVariable: 'GERRIT_PASSWORD', usernameVariable: 'GERRIT_USERNAME')]) {
                  sh '''
                    set +x
                    echo "AAOS CACHE Persistent Volume Claim: ${NODE_NAME}-aaos-cache" | tee -a build_cache_volume.txt
                    /usr/bin/kubectl get pod ${NODE_NAME} -n jenkins -o=jsonpath='{.spec.nodeName}' | xargs -I {} gcloud compute instances describe {} --zone=${CLOUD_ZONE} | grep 'deviceName: pvc' | awk '{print "AAOS CACHE Persistent Volume: " $2}' | tee -a build_cache_volume.txt || true
                  '''
                  sh '''
                    git config --global credential.helper store
                    git config --global url."https://${GERRIT_USERNAME}@${HORIZON_DOMAIN}/gerrit".insteadOf "https://${HORIZON_DOMAIN}/gerrit"
                    echo https://"${GERRIT_USERNAME}":"${GERRIT_PASSWORD}"@"${HORIZON_DOMAIN}/gerrit" > ~/.git-credentials

                    AAOS_GERRIT_MANIFEST_URL="${AAOS_GERRIT_MANIFEST_URL}" \
                    AAOS_REVISION="${AAOS_REVISION}" \
                    AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                    AAOS_CLEAN="NO_CLEAN" \
                    GERRIT_SERVER_URL="${GERRIT_API_URL}" \
                    GERRIT_USERNAME="${GERRIT_USERNAME}" \
                    GERRIT_PASSWORD="${GERRIT_PASSWORD}" \
                    POST_REPO_INITIALISE_COMMAND="${POST_REPO_INITIALISE_COMMAND}" \
                    POST_REPO_COMMAND="${POST_REPO_COMMAND}" \
                    REPO_SYNC_JOBS="${GERRIT_REPO_SYNC_JOBS}" \
                    USE_LOCAL_AOSP_MIRROR="${USE_LOCAL_AOSP_MIRROR}" \
                    MIRROR_DIR_FULL_PATH="${AOSP_MIRROR_PRESET_FILESTORE_PVC_MOUNT_PATH_IN_CONTAINER}/${AOSP_MIRROR_PRESET_MIRROR_ROOT_SUBDIR_NAME}/${AOSP_MIRROR_DIR_NAME}" \
                    ./workloads/android/pipelines/builds/aaos_builder/aaos_initialise.sh
                  '''
                }
              }
              archiveArtifacts artifacts: 'build_cache*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
            }
          }
        }

        stage ('Build'){
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_BUILD_CTS=${AAOS_BUILD_CTS} \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_build.sh
                '''
              }
            }
          }
        }

        stage ('Storage') {
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { env.AAOS_ARTIFACT_STORAGE_SOLUTION }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_REVISION="${AAOS_REVISION}" \
                  ANDROID_VERSION="${SDK_ANDROID_VERSION}" \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_avd_sdk.sh || true

                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_ARTIFACT_ROOT_NAME="${ANDROID_BUILD_BUCKET_ROOT_NAME}" \
                  AAOS_ARTIFACT_STORAGE_SOLUTION="${AAOS_ARTIFACT_STORAGE_SOLUTION}" \
                  STORAGE_BUCKET_DESTINATION="${STORAGE_BUCKET_DESTINATION}" \
                  STORAGE_LABELS="${STORAGE_LABELS}" \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_storage.sh
                '''
                archiveArtifacts artifacts: '*artifacts*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              }
            }
          }
        }

        stage ('Retain instance') {
          when { expression { env.AAOS_LUNCH_TARGET } }
          steps {
            container(name: 'builder') {
              script {
                sleep(time: "${INSTANCE_RETENTION_TIME}", unit: 'MINUTES')
              }
            }
          }
        }
      }
    }
  }
}
